---
title: Project Managment Planning
output: html_document
---
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

<br>


`r emo::ji("white large square")` Roles and Responsibilities

- Who will create the documentation
  - Who is best suited to provide the information for each particular document
- Who will submit measures to the IRB
- Who is creating instruments
- Who will download data
- Who will create data entry files
- Who will enter data
- Who will send that data and who will receive external source data (ex: from a district)
- Who will create data storage structures
- Who is in charge of adding and removing access
- Who is in charge of ensuring the team reviews the data sharing/access/use policies
- Who will oversee that this protocol is followed

`r emo::ji("white large square")` Documentation

- What documentation do we plan to create
  - Consider team, project, dataset, and variable level documentation
- When do we plan to create it
- What documentation is needed before a project starts, what is needed before we share data
- What format will the documentation be in
- Are there requirements from your future repository
- Are there limitations based on tools you have access to
- Where will we store documentation
- Who will create the tracking database
- Who will track data

`r emo::ji("white large square")` Instruments

- Consent forms and MOUs
- What data sharing language will be included What language about confidentiality
- Who will submit the forms to IRB
- Add this to Roles and Responsibilities
- What measures are we collecting
- How are we collecting each measure Paper or electronic What tools will be used
- What scales will be included
- How are we verifying tools


`r emo::ji("white large square")` Tracking

- What tool will we use to track participants in our study
  - Ex: FileMaker, Microsoft Access, Basecamp
- How will we structure the database
  - One table for each participant
  - One table per data collection wave
- What fields will we include
  - Identifying information, study ID, data collection instruments
- How will we assign study IDs
  - Numeric or alphanumeric
  - How many digits
  - What starting number

`r emo::ji("white large square")` Data Capture

- How will you extract electronic data
  - Download, API
  - What format
- How will you convert paper data into an electronic format
- What databases need to be created and protocols designed for data entry
- What external data will you be receiving
  - What format will that be in Will there be a data dictionary associated
- What information is needed to supplement data
  - Random assignment
  - Study ID
  - Completion numbers
  
`r emo::ji("white large square")` Storage

- How and where will we store paper data
  - Consider IRB requirements
  - What will the structure be
  - Who will oversee that this protocol is followed
- How and where will we store electronic data
  - Consider IRB requirements
  - What will the structure be
  - Who will have access


`r emo::ji("white large square")` Data Cleaning

- What tool/s will you use to clean and validate data
  - What tools are available to you
  - What is the skill level of team members
- Will there be code review
- Gather the information required to create your data cleaning plan
  - How will you access data
  - What format/file type will raw data be in
  - How reliable will the data be
  - What is the timeline for receiving data
  - What structure do researchers want their data in Long or wide
  - What file types should final data be in
    - Take into consideration the requirements of a future repository as well as the needs of internal users
  - Any additional calculations or transformations required for the data
  - How should missing data be coded
  - Any other secondary sources need to be brought in to enhance the data
  - What is the timeline for when clean data is needed
