---
title: Project Managment Planning
output: html_document
---
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>

<br>

`r emo::ji("white large square")` Roles and Responsibilities  

- Who is in charge of hiring? Supervision?
- Who is in charge of training?
- Who monitors CITI IRB completion for staff?
- Who recruits participants?
- Who implements the intervention?
- Who creates data collection materials?
- Who will schedule and oversee data collection?
- Who will collect data?

`r emo::ji("white large square")` Hiring  

- Full-time staff  
- Contractual staff  

`r emo::ji("white large square")` Training  

- CITI  
- Data Collection  

`r emo::ji("white large square")` Recruitment  

- Where from and how are we recruiting participants  
- How are participants being consented  
- How are participants being randomly assigned

`r emo::ji("white large square")` Intervention Implementation  

- Is there an intervention being implemented  
- Who is supervising that  
- How is that being implemented  

`r emo::ji("white large square")` Materials  

- What physical materials do you need  
- Testing materials  
- Books/papers/pens  
- What forms do you need to make  
- What accounts do you need to set up 

`r emo::ji("white large square")` How will data be collected  

- In person/remote  

`r emo::ji("white large square")` Data collection scheduling  

- What tools will you use to schedule data collection  
- How will you communicate with staff and participants about data collection  

  